version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: user_service_backend_db
    volumes:
      - ./db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    env_file:
      - .env.sample
    ports:
      - "5432:5432"
  api:
    build:
      context: .
    command: >
      sh -c "python manage.py db init &&
             python manage.py db migrate &&
             python manage.py db upgrade
             gunicorn manage:app"
    env_file:
      - .env.sample
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data: